Fix syntax for pip installation
step 9 of building the docker image threw errors because:
`ValueError("Expected "+item_name+" in",line,"at",line[p:])
ValueError: ('Expected version spec in', 'Cython=0.19.2', 'at', '=0.19.2')`
for all packages in requirements.txt except `python-dateutil>=1.4,<2` of which the syntax is correct.